### ISSUE TITLE
run exmaple error

### ISSUE THREAD

**Issue by tornadomeet** [tqchen/tinyflow#4]
Hello, 
my torch is installed correct(can run) and tinyflow is build ok, `libtinyflow.so` is in `./lib/`.

when run example with this cmd:

``` shell
export LD_LIBRARY_PATH=/home/work/wuwei/project/torch/install/lib:${LD_LIBRARY_PATH}
export PYTHONPATH=${PYTHONPATH}:/home/work/wuwei/project/dmlc/tinyflow/python:/home/work/wuwei/project/dmlc/nnvm/python
python -u mnist_softmax.py
```

it will output the error log:

```
Traceback (most recent call last):
  File "mnist_softmax.py", line 5, in <module>
    import tinyflow as tf
  File "/home/work/wuwei/project/dmlc/tinyflow/python/tinyflow/__init__.py", line 3, in <module>
    from . import _base
  File "/home/work/wuwei/project/dmlc/tinyflow/python/tinyflow/_base.py", line 24, in <module>
    from nnvm.name import NameManager
  File "/home/work/wuwei/project/dmlc/nnvm/python/nnvm/__init__.py", line 6, in <module>
    from . import _base
  File "/home/work/wuwei/project/dmlc/nnvm/python/nnvm/_base.py", line 43, in <module>
    _LIB = _load_lib()
  File "/home/work/wuwei/project/dmlc/nnvm/python/nnvm/_base.py", line 35, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_GLOBAL)
  File "/usr/lib64/python2.7/ctypes/__init__.py", line 360, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/work/wuwei/project/torch/install/lib/libTHC.so: undefined symbol: THC_float2half
```

it should be the libTHC.so can not found by tinyflow, but  i had add it to the environment and this file is  also exist. 
and i found when using `ldd libs/lib/libtinyflow.so`, log is 

```
    linux-vdso.so.1 =>  (0x00007fff415fe000)
    /lib64/libharfbuzz.so (0x00007fc8044e0000)
    libluajit.so => /home/work/wuwei/project/torch/install/lib/libluajit.so (0x00007fc804246000)
    libluaT.so => /home/work/wuwei/project/torch/install/lib/libluaT.so (0x00007fc80403d000)
    libTH.so => /home/work/wuwei/project/torch/install/lib/libTH.so (0x00007fc803bd6000)
    libTHC.so => /home/work/wuwei/project/torch/install/lib/libTHC.so (0x00007fc801cc4000)
    libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fc8019bc000)
    libm.so.6 => /lib64/libm.so.6 (0x00007fc8016b9000)
    libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fc8014a3000)
    libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fc801287000)
    libc.so.6 => /lib64/libc.so.6 (0x00007fc800ec5000)
    /lib64/ld-linux-x86-64.so.2 (0x00007fc804a77000)
    libglib-2.0.so.0 => /lib64/libglib-2.0.so.0 (0x00007fc800b8e000)
    libfreetype.so.6 => /lib64/libfreetype.so.6 (0x00007fc8008e8000)
    libgraphite2.so.3 => /lib64/libgraphite2.so.3 (0x00007fc8006cb000)
    libreadline.so.6 => /lib64/libreadline.so.6 (0x00007fc800485000)
    libdl.so.2 => /lib64/libdl.so.2 (0x00007fc800281000)
    libgomp.so.1 => /lib64/libgomp.so.1 (0x00007fc800069000)
    libopenblas.so.0 => /opt/OpenBLAS/lib/libopenblas.so.0 (0x00007fc7ff037000)
    librt.so.1 => /lib64/librt.so.1 (0x00007fc7fee2e000)
    libcublas.so.7.5 => /usr/local/cuda/lib64/libcublas.so.7.5 (0x00007fc7fd54f000)
    libcurand.so.7.5 => /usr/local/cuda/lib64/libcurand.so.7.5 (0x00007fc7f9ce7000)
    libtinfo.so.5 => /lib64/libtinfo.so.5 (0x00007fc7f9abc000)
    libgfortran.so.3 => /lib64/libgfortran.so.3 (0x00007fc7f979a000)
    libquadmath.so.0 => /lib64/libquadmath.so.0 (0x00007fc7f955d000)
```

so `/home/work/wuwei/project/torch/install/lib/libTHC.so` is linked.

**Comment by tornadomeet** [comment]
fixed `undefined symbol: THC_float2half` error by https://github.com/torch/cutorch/issues/376
